# Generated by Django 5.1.6 on 2025-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_user_customuser_message_delete_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
