# Generated by Django 5.1.6 on 2025-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_message_options_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('portfolio', models.URLField()),
            ],
        ),
    ]
